# Generated by Django 5.1 on 2024-09-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_topic_uploadedfile_uploaded_at_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_desc',
            field=models.CharField(default='No description', max_length=255),
        ),
    ]
